# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: docker login
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: create docker image
      run: docker build -t helloworld-image .
    - name: push to docker hub
      run: |
        docker tag helloworld-image rohitsinghhoneywell/myrepo:1.0
        docker push rohitsinghhoneywell/myrepo:1.0
    #- name: push to nexus
    #  run: |
    #    docker tag helloworld-image nat01.encowayhb.lokal:5002/mosaiq-store/mosaiq-store:latest
    #    docker push nat01.encowayhb.lokal:5002/mosaiq-store/mosaiq-store:latest
      
      
      
