# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build the latest Docker image
      run: docker build -t rohitsinghhoneywell/myrepo:rohit_sample_1 .
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME  }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD  }}
      run: winpty docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
